### ISSUE TITLE
Images with resizeMode "cover" loses its borderRadius

### ISSUE THREAD

**Issue by t1mp4** [lightning-tv/core#18]
(Not sure if "issue" or "question")

Images with resizeMode "cover" loses its borderRadius.

This is expected because it clips the element, however, it would be nice if it would keep the borderRadius.

```js
<View style={{ width: 300, height: 300, borderRadius: 12 }}>
    <View
        src="http://some-external-site.com/image.png"
        textureOptions={{
            resizeMode: {
                type: "cover"
            }
        }}
        borderRadius={12}
    />
</View>
```

My workaround right now is to add a transparent overlay with a border and border radius, but it's wonky.

Is there a better method?

**Comment by chiefcll** [comment]
I see - this is most likely an issue in the https://github.com/lightning-js/renderer - I'm just passing those options through. Glad it's all "working" though - this is my first time seeing textureOptions but that should all be wired up correctly on Solid & Core side. Sometimes borderRadius is wonky because the order it's added will affect other dynamic shaders as well (like linearGradient etc)

**Comment by chiefcll** [comment]
It looks like this is working in the renderer...
Original:
<img width="951" alt="image" src="https://github.com/user-attachments/assets/09e5ea0f-afce-4fb6-b875-f2577b821c1a">

With radius
<img width="941" alt="image" src="https://github.com/user-attachments/assets/4e7e8da2-dd1f-4df1-8de4-6e54837b3056">

Is this what you're expecting? Can you upload images

**Comment by chiefcll** [comment]
I see - yes this is a render question / issue...

<img width="957" alt="image" src="https://github.com/user-attachments/assets/9f5afb39-d547-4c8a-9419-9671ce7ba8cc">

This is radius 16 - not rounding at all. Extreme value will eventually round.

**Comment by chiefcll** [comment]
Reposted to Lightning Renderer: https://github.com/lightning-js/renderer/issues/357
